# Generated by Django 4.0.2 on 2022-05-02 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Signin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_name', models.CharField(max_length=50, verbose_name='First Name')),
                ('Last_name', models.CharField(max_length=50, verbose_name='Last Name')),
                ('Email_id', models.EmailField(max_length=150, verbose_name='Email id')),
                ('Phone_no', models.CharField(max_length=50, verbose_name='Phone number')),
                ('Password', models.CharField(max_length=50, verbose_name='Password')),
            ],
        ),
    ]
