# Generated by Django 4.0.2 on 2022-05-03 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venuehome', '0002_seminarhall'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mondini_Hall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Event', models.CharField(max_length=200, verbose_name='Event ')),
                ('Department', models.CharField(max_length=200)),
                ('Date', models.DateField(verbose_name='Event Date')),
                ('Start_time', models.TimeField(verbose_name='Start time')),
                ('Estimated_people', models.CharField(max_length=200, verbose_name='No of people attending ')),
                ('no_of_chairs', models.CharField(max_length=200, verbose_name='No of chairs required ')),
                ('Projector', models.CharField(max_length=20)),
                ('Any_requirements', models.TextField(blank=True, verbose_name='Specify Requirements if any')),
            ],
        ),
    ]
