# Generated by Django 4.0.4 on 2022-05-09 12:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('venuehome', '0004_boscohall_ground'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seminarhall',
            name='End_time',
        ),
        migrations.RemoveField(
            model_name='seminarhall',
            name='Start_time',
        ),
        migrations.CreateModel(
            name='SeminarBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Start_time', models.DateTimeField(verbose_name='Start time')),
                ('End_time', models.DateTimeField(verbose_name='End time')),
                ('hall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='venuehome.seminarhall')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
