# Generated by Django 4.0.4 on 2022-05-12 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('venuehome', '0006_venue_booking'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BoscoHall',
        ),
        migrations.DeleteModel(
            name='Ground',
        ),
        migrations.DeleteModel(
            name='Mondini_Hall',
        ),
        migrations.DeleteModel(
            name='SeminarBooking',
        ),
        migrations.DeleteModel(
            name='SeminarHall',
        ),
    ]
