# Generated by Django 4.0.4 on 2022-05-12 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venuehome', '0007_delete_boscohall_delete_ground_delete_mondini_hall_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='Projector',
            field=models.CharField(max_length=1, verbose_name='Projector required'),
        ),
    ]
